### ISSUE TITLE
hard coded samtools path

### ISSUE THREAD

**Issue by edgreen72** [svohr/tilde#1]
line 92 of make_obs_table constructs the samtools mpileup command.
The path to the samtools executable is hard-coded as /usr/local/bin/samtools

This enforces a narrow-minded view of where samtools ought to be. What if I don't even have a /usr/local/bin directory?
What is I want my samtools executable to be elsewhere?

Linux has a concept of PATH. Why not change the call to samtools to be free of a hard-coded location and simply find the version that is in my PATH?

**Comment by svohr** [comment]
That's reasonable. It was probably hardcoded because there were several `samtools` versions installed on the server and I wanted to make sure I was using the right one.
